# Generated by Django 5.1.3 on 2024-11-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('meta', models.TextField(blank=True, max_length=455)),
                ('thumbnail', models.ImageField(upload_to='sort/cat/%Y-%m/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sort.category')),
            ],
        ),
    ]
