# Generated by Django 5.1.3 on 2024-11-22 08:47

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediastore', '0001_initial'),
        ('sort', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('meta', models.TextField(blank=True, max_length=400)),
                ('amount', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.SlugField(max_length=255, unique=True)),
                ('thumbnail', models.ImageField(max_length=500, upload_to='store/products/%Y-%m')),
                ('meta', models.TextField(max_length=400)),
                ('total', models.SmallIntegerField(blank=True, default=0)),
                ('org_price', models.IntegerField(default=0)),
                ('discount', models.SmallIntegerField(default=0)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('status', models.CharField(choices=[('T', 'Published'), ('F', 'Draft')], default='F', max_length=1)),
                ('Tags', models.ManyToManyField(blank=True, to='sort.tag')),
                ('buyers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='sort.category')),
                ('details', models.ManyToManyField(to='store.detail')),
                ('discount_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.discountgroup')),
                ('images', models.ManyToManyField(blank=True, to='mediastore.image')),
                ('videos', models.ManyToManyField(blank=True, to='mediastore.video')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('products', models.ManyToManyField(blank=True, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.SmallIntegerField(default=0)),
                ('comment', models.TextField(max_length=500)),
                ('show', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='store.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
