# Generated by Django 5.1.3 on 2024-11-22 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastore', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.ManyToManyField(blank=True, null=True, to='store.detail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(null=True, to='mediastore.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='store/defaults/product.png', max_length=500, upload_to='store/products/%Y-%m'),
        ),
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(null=True, to='mediastore.video'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
