# Generated by Django 5.1.3 on 2024-11-22 10:44

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastore', '0001_initial'),
        ('store', '0002_alter_product_details_alter_product_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.SmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.ManyToManyField(to='store.detail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='mediastore.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('T', 'Published'), ('F', 'Draft'), ('A', 'Archived')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(to='mediastore.video'),
        ),
        migrations.AddField(
            model_name='product',
            name='int_detail',
            field=models.ManyToManyField(to='store.intdetail'),
        ),
    ]
