# Generated by Django 5.1.3 on 2024-11-22 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastore', '0001_initial'),
        ('store', '0003_intdetail_remove_product_total_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buyers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.ManyToManyField(blank=True, to='store.detail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='mediastore.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='int_detail',
            field=models.ManyToManyField(blank=True, to='store.intdetail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(blank=True, to='mediastore.video'),
        ),
    ]
