# Generated by Django 5.1.3 on 2024-11-21 20:35

import django.db.models.deletion
import django_ckeditor_5.fields
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sort', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('address', models.SlugField(max_length=255, unique=True)),
                ('meta', models.TextField(max_length=400)),
                ('thumbnail', models.ImageField(blank=True, max_length=255, upload_to='thumbnails_%Y/')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Published'), ('D', 'Draft'), ('A', 'Archived')], default='D', max_length=1)),
                ('read_time', models.SmallIntegerField()),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('last_modified', django_jalali.db.models.jDateField(auto_now=True)),
                ('open_conv', models.BooleanField(default=True, verbose_name='Open Converstaion')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(blank=True, to='sort.category')),
                ('likes', models.ManyToManyField(related_name='viewed', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='sort.tag')),
                ('views', models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_modified',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='D', max_length=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
            ],
        ),
    ]
