# Generated by Django 5.1.3 on 2024-11-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, upload_to='blog/thumbnails-%Y/'),
        ),
    ]
