# Generated by Django 5.1.3 on 2024-12-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='biography',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='users/prof/%Y-%m/'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
